// Code generated by protoc-gen-go. DO NOT EDIT.
// source: member.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MemberCreateRequest struct {
	Uniacid              int64    `protobuf:"zigzag64,1,opt,name=uniacid,proto3" json:"uniacid,omitempty"`
	Mobile               string   `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Pwd                  string   `protobuf:"bytes,3,opt,name=pwd,proto3" json:"pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemberCreateRequest) Reset()         { *m = MemberCreateRequest{} }
func (m *MemberCreateRequest) String() string { return proto.CompactTextString(m) }
func (*MemberCreateRequest) ProtoMessage()    {}
func (*MemberCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{0}
}

func (m *MemberCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberCreateRequest.Unmarshal(m, b)
}
func (m *MemberCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberCreateRequest.Marshal(b, m, deterministic)
}
func (m *MemberCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberCreateRequest.Merge(m, src)
}
func (m *MemberCreateRequest) XXX_Size() int {
	return xxx_messageInfo_MemberCreateRequest.Size(m)
}
func (m *MemberCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MemberCreateRequest proto.InternalMessageInfo

func (m *MemberCreateRequest) GetUniacid() int64 {
	if m != nil {
		return m.Uniacid
	}
	return 0
}

func (m *MemberCreateRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *MemberCreateRequest) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type MemberCreateReply struct {
	Uniacid              int64    `protobuf:"zigzag64,1,opt,name=uniacid,proto3" json:"uniacid,omitempty"`
	Id                   int64    `protobuf:"zigzag64,2,opt,name=id,proto3" json:"id,omitempty"`
	Openid               string   `protobuf:"bytes,3,opt,name=openid,proto3" json:"openid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemberCreateReply) Reset()         { *m = MemberCreateReply{} }
func (m *MemberCreateReply) String() string { return proto.CompactTextString(m) }
func (*MemberCreateReply) ProtoMessage()    {}
func (*MemberCreateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{1}
}

func (m *MemberCreateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberCreateReply.Unmarshal(m, b)
}
func (m *MemberCreateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberCreateReply.Marshal(b, m, deterministic)
}
func (m *MemberCreateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberCreateReply.Merge(m, src)
}
func (m *MemberCreateReply) XXX_Size() int {
	return xxx_messageInfo_MemberCreateReply.Size(m)
}
func (m *MemberCreateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberCreateReply.DiscardUnknown(m)
}

var xxx_messageInfo_MemberCreateReply proto.InternalMessageInfo

func (m *MemberCreateReply) GetUniacid() int64 {
	if m != nil {
		return m.Uniacid
	}
	return 0
}

func (m *MemberCreateReply) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MemberCreateReply) GetOpenid() string {
	if m != nil {
		return m.Openid
	}
	return ""
}

type MemberInfoByMobileRequest struct {
	Uniacid              int64    `protobuf:"zigzag64,1,opt,name=uniacid,proto3" json:"uniacid,omitempty"`
	Mobile               string   `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Pwd                  string   `protobuf:"bytes,3,opt,name=pwd,proto3" json:"pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemberInfoByMobileRequest) Reset()         { *m = MemberInfoByMobileRequest{} }
func (m *MemberInfoByMobileRequest) String() string { return proto.CompactTextString(m) }
func (*MemberInfoByMobileRequest) ProtoMessage()    {}
func (*MemberInfoByMobileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{2}
}

func (m *MemberInfoByMobileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberInfoByMobileRequest.Unmarshal(m, b)
}
func (m *MemberInfoByMobileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberInfoByMobileRequest.Marshal(b, m, deterministic)
}
func (m *MemberInfoByMobileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberInfoByMobileRequest.Merge(m, src)
}
func (m *MemberInfoByMobileRequest) XXX_Size() int {
	return xxx_messageInfo_MemberInfoByMobileRequest.Size(m)
}
func (m *MemberInfoByMobileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberInfoByMobileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MemberInfoByMobileRequest proto.InternalMessageInfo

func (m *MemberInfoByMobileRequest) GetUniacid() int64 {
	if m != nil {
		return m.Uniacid
	}
	return 0
}

func (m *MemberInfoByMobileRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *MemberInfoByMobileRequest) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type MemberInfoReply struct {
	Id                   int64    `protobuf:"zigzag64,1,opt,name=id,proto3" json:"id,omitempty"`
	Uniacid              int64    `protobuf:"zigzag64,2,opt,name=uniacid,proto3" json:"uniacid,omitempty"`
	Uid                  int64    `protobuf:"zigzag64,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Openid               string   `protobuf:"bytes,4,opt,name=openid,proto3" json:"openid,omitempty"`
	Realname             string   `protobuf:"bytes,5,opt,name=realname,proto3" json:"realname,omitempty"`
	Mobile               string   `protobuf:"bytes,6,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Weixin               string   `protobuf:"bytes,7,opt,name=weixin,proto3" json:"weixin,omitempty"`
	Createtime           int64    `protobuf:"zigzag64,8,opt,name=createtime,proto3" json:"createtime,omitempty"`
	Status               int64    `protobuf:"zigzag64,9,opt,name=status,proto3" json:"status,omitempty"`
	Nickname             string   `protobuf:"bytes,10,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Gender               int64    `protobuf:"zigzag64,11,opt,name=gender,proto3" json:"gender,omitempty"`
	Avatar               string   `protobuf:"bytes,12,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Province             string   `protobuf:"bytes,13,opt,name=province,proto3" json:"province,omitempty"`
	City                 string   `protobuf:"bytes,14,opt,name=city,proto3" json:"city,omitempty"`
	Area                 string   `protobuf:"bytes,15,opt,name=area,proto3" json:"area,omitempty"`
	Salt                 string   `protobuf:"bytes,16,opt,name=salt,proto3" json:"salt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemberInfoReply) Reset()         { *m = MemberInfoReply{} }
func (m *MemberInfoReply) String() string { return proto.CompactTextString(m) }
func (*MemberInfoReply) ProtoMessage()    {}
func (*MemberInfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{3}
}

func (m *MemberInfoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberInfoReply.Unmarshal(m, b)
}
func (m *MemberInfoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberInfoReply.Marshal(b, m, deterministic)
}
func (m *MemberInfoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberInfoReply.Merge(m, src)
}
func (m *MemberInfoReply) XXX_Size() int {
	return xxx_messageInfo_MemberInfoReply.Size(m)
}
func (m *MemberInfoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberInfoReply.DiscardUnknown(m)
}

var xxx_messageInfo_MemberInfoReply proto.InternalMessageInfo

func (m *MemberInfoReply) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MemberInfoReply) GetUniacid() int64 {
	if m != nil {
		return m.Uniacid
	}
	return 0
}

func (m *MemberInfoReply) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *MemberInfoReply) GetOpenid() string {
	if m != nil {
		return m.Openid
	}
	return ""
}

func (m *MemberInfoReply) GetRealname() string {
	if m != nil {
		return m.Realname
	}
	return ""
}

func (m *MemberInfoReply) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *MemberInfoReply) GetWeixin() string {
	if m != nil {
		return m.Weixin
	}
	return ""
}

func (m *MemberInfoReply) GetCreatetime() int64 {
	if m != nil {
		return m.Createtime
	}
	return 0
}

func (m *MemberInfoReply) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *MemberInfoReply) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *MemberInfoReply) GetGender() int64 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *MemberInfoReply) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *MemberInfoReply) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *MemberInfoReply) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *MemberInfoReply) GetArea() string {
	if m != nil {
		return m.Area
	}
	return ""
}

func (m *MemberInfoReply) GetSalt() string {
	if m != nil {
		return m.Salt
	}
	return ""
}

func init() {
	proto.RegisterType((*MemberCreateRequest)(nil), "api.MemberCreateRequest")
	proto.RegisterType((*MemberCreateReply)(nil), "api.MemberCreateReply")
	proto.RegisterType((*MemberInfoByMobileRequest)(nil), "api.MemberInfoByMobileRequest")
	proto.RegisterType((*MemberInfoReply)(nil), "api.MemberInfoReply")
}

func init() { proto.RegisterFile("member.proto", fileDescriptor_9b9836b7e13de206) }

var fileDescriptor_9b9836b7e13de206 = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0x4f, 0xce, 0xd3, 0x30,
	0x10, 0xc5, 0x49, 0xf2, 0x91, 0xb6, 0x43, 0xff, 0x31, 0xa0, 0xca, 0x74, 0x51, 0x55, 0x59, 0x75,
	0xd5, 0x05, 0xdc, 0xa0, 0xac, 0x90, 0xe8, 0x26, 0x88, 0x05, 0x2b, 0xe4, 0x26, 0x03, 0xb2, 0x48,
	0x1c, 0xe3, 0x38, 0x2d, 0x39, 0x04, 0x87, 0xe0, 0xa6, 0xc8, 0x76, 0x52, 0x52, 0xa8, 0x58, 0x7d,
	0xbb, 0x79, 0x6f, 0xe2, 0x37, 0x3f, 0x27, 0x13, 0x98, 0x96, 0x54, 0x9e, 0x48, 0xef, 0x95, 0xae,
	0x4c, 0x85, 0x11, 0x57, 0x22, 0xf9, 0x04, 0x2f, 0x8e, 0xce, 0x7c, 0xab, 0x89, 0x1b, 0x4a, 0xe9,
	0x7b, 0x43, 0xb5, 0x41, 0x06, 0xa3, 0x46, 0x0a, 0x9e, 0x89, 0x9c, 0x05, 0xdb, 0x60, 0x87, 0x69,
	0x2f, 0x71, 0x05, 0x71, 0x59, 0x9d, 0x44, 0x41, 0x2c, 0xdc, 0x06, 0xbb, 0x49, 0xda, 0x29, 0x5c,
	0x42, 0xa4, 0x2e, 0x39, 0x8b, 0x9c, 0x69, 0xcb, 0xe4, 0x23, 0x3c, 0xbf, 0x8d, 0x56, 0x45, 0xfb,
	0x9f, 0xe0, 0x39, 0x84, 0x22, 0x77, 0xa1, 0x98, 0x86, 0x7e, 0x50, 0xa5, 0x48, 0x8a, 0x3e, 0xb3,
	0x53, 0xc9, 0x67, 0x78, 0xe5, 0x63, 0xdf, 0xc9, 0x2f, 0xd5, 0xa1, 0x3d, 0xba, 0xf1, 0x8f, 0xc9,
	0xfd, 0x33, 0x82, 0xc5, 0x9f, 0x09, 0x1e, 0xdb, 0xc3, 0x05, 0x57, 0xb8, 0xc1, 0x9c, 0xf0, 0x76,
	0xce, 0x12, 0xa2, 0xa6, 0x63, 0xc6, 0xd4, 0x96, 0x83, 0x8b, 0x3c, 0x0c, 0x2f, 0x82, 0x6b, 0x18,
	0x6b, 0xe2, 0x85, 0xe4, 0x25, 0xb1, 0xa7, 0xae, 0x73, 0xd5, 0x03, 0xda, 0xf8, 0x86, 0x76, 0x05,
	0xf1, 0x85, 0xc4, 0x0f, 0x21, 0xd9, 0xc8, 0xfb, 0x5e, 0xe1, 0x06, 0x20, 0x73, 0x6f, 0xd9, 0x88,
	0x92, 0xd8, 0xd8, 0x0d, 0x1f, 0x38, 0xf6, 0x5c, 0x6d, 0xb8, 0x69, 0x6a, 0x36, 0x71, 0xbd, 0x4e,
	0x59, 0x06, 0x29, 0xb2, 0x6f, 0x8e, 0x01, 0x3c, 0x43, 0xaf, 0xed, 0x99, 0xaf, 0x24, 0x73, 0xd2,
	0xec, 0x99, 0x3f, 0xe3, 0x95, 0xf5, 0xf9, 0x99, 0x1b, 0xae, 0xd9, 0xd4, 0x33, 0x78, 0x65, 0xb3,
	0x94, 0xae, 0xce, 0x42, 0x66, 0xc4, 0x66, 0x3e, 0xab, 0xd7, 0x88, 0xf0, 0x90, 0x09, 0xd3, 0xb2,
	0xb9, 0xf3, 0x5d, 0x6d, 0x3d, 0xae, 0x89, 0xb3, 0x85, 0xf7, 0x6c, 0x6d, 0xbd, 0x9a, 0x17, 0x86,
	0x2d, 0xbd, 0x67, 0xeb, 0xd7, 0xbf, 0x02, 0x98, 0xf9, 0xef, 0xf1, 0x81, 0xf4, 0x59, 0x64, 0x84,
	0x07, 0x98, 0x0e, 0x37, 0x0b, 0xd9, 0x9e, 0x2b, 0xb1, 0xbf, 0xb3, 0xc7, 0xeb, 0xd5, 0x9d, 0x8e,
	0x2a, 0xda, 0xe4, 0x09, 0xbe, 0x07, 0xfc, 0x77, 0x8d, 0x70, 0x33, 0x78, 0xfe, 0xce, 0x7e, 0xad,
	0x5f, 0xfe, 0xd5, 0xef, 0xd2, 0x4e, 0xb1, 0xfb, 0xa5, 0xde, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff,
	0x50, 0xfc, 0xa2, 0xec, 0x62, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MemberServiceClient is the client API for MemberService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MemberServiceClient interface {
	MemberCreate(ctx context.Context, in *MemberCreateRequest, opts ...grpc.CallOption) (*MemberCreateReply, error)
	MemberInfoByMobile(ctx context.Context, in *MemberInfoByMobileRequest, opts ...grpc.CallOption) (*MemberInfoReply, error)
}

type memberServiceClient struct {
	cc *grpc.ClientConn
}

func NewMemberServiceClient(cc *grpc.ClientConn) MemberServiceClient {
	return &memberServiceClient{cc}
}

func (c *memberServiceClient) MemberCreate(ctx context.Context, in *MemberCreateRequest, opts ...grpc.CallOption) (*MemberCreateReply, error) {
	out := new(MemberCreateReply)
	err := c.cc.Invoke(ctx, "/api.MemberService/MemberCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberServiceClient) MemberInfoByMobile(ctx context.Context, in *MemberInfoByMobileRequest, opts ...grpc.CallOption) (*MemberInfoReply, error) {
	out := new(MemberInfoReply)
	err := c.cc.Invoke(ctx, "/api.MemberService/MemberInfoByMobile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MemberServiceServer is the server API for MemberService service.
type MemberServiceServer interface {
	MemberCreate(context.Context, *MemberCreateRequest) (*MemberCreateReply, error)
	MemberInfoByMobile(context.Context, *MemberInfoByMobileRequest) (*MemberInfoReply, error)
}

func RegisterMemberServiceServer(s *grpc.Server, srv MemberServiceServer) {
	s.RegisterService(&_MemberService_serviceDesc, srv)
}

func _MemberService_MemberCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemberCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServiceServer).MemberCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MemberService/MemberCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServiceServer).MemberCreate(ctx, req.(*MemberCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberService_MemberInfoByMobile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemberInfoByMobileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServiceServer).MemberInfoByMobile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MemberService/MemberInfoByMobile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServiceServer).MemberInfoByMobile(ctx, req.(*MemberInfoByMobileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MemberService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.MemberService",
	HandlerType: (*MemberServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MemberCreate",
			Handler:    _MemberService_MemberCreate_Handler,
		},
		{
			MethodName: "MemberInfoByMobile",
			Handler:    _MemberService_MemberInfoByMobile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "member.proto",
}
