package model

import (
	"mall/lib/time"
)

type EweiShopOrder struct {
	Id                   int       `gorm:"primary_key;AUTO_INCREMENT" json:"id"`
	Uniacid              int       `json:"uniacid"`
	Openid               string    `json:"openid"`
	Agentid              int       `json:"agentid"`
	Ordersn              string    `json:"ordersn"`
	Price                float64   `json:"price"`
	Goodsprice           float64   `json:"goodsprice"`
	Discountprice        float64   `json:"discountprice"`
	Status               int       `json:"status"`
	Paytype              int       `json:"paytype"`
	Transid              string    `json:"transid"`
	Remark               string    `json:"remark"`
	Addressid            int       `json:"addressid"`
	Dispatchprice        float64   `json:"dispatchprice"`
	Dispatchid           int       `json:"dispatchid"`
	Createtime           time.Time `json:"createtime"`
	Dispatchtype         int       `json:"dispatchtype"`
	Carrier              string    `json:"carrier"`
	Refundid             int       `json:"refundid"`
	Iscomment            int       `json:"iscomment"`
	Creditadd            int       `json:"creditadd"`
	Deleted              int       `json:"deleted"`
	Userdeleted          int       `json:"userdeleted"`
	Finishtime           time.Time `json:"finishtime"`
	Paytime              time.Time `json:"paytime"`
	Expresscom           string    `json:"expresscom"`
	Expresssn            string    `json:"expresssn"`
	Express              string    `json:"express"`
	Sendtime             time.Time `json:"sendtime"`
	Fetchtime            time.Time `json:"fetchtime"`
	Cash                 int       `json:"cash"`
	Canceltime           time.Time `json:"canceltime"`
	Cancelpaytime        time.Time `json:"cancelpaytime"`
	Refundtime           time.Time `json:"refundtime"`
	Isverify             int       `json:"isverify"`
	Verified             int       `json:"verified"`
	Verifyopenid         string    `json:"verifyopenid"`
	Verifycode           string    `json:"verifycode"`
	Verifytime           time.Time `json:"verifytime"`
	Verifystoreid        int       `json:"verifystoreid"`
	Deductprice          float64   `json:"deductprice"`
	Deductcredit         int       `json:"deductcredit"`
	Deductcredit2        float64   `json:"deductcredit2"`
	Deductenough         float64   `json:"deductenough"`
	Virtual              int       `json:"virtual"`
	VirtualInfo          string    `json:"virtual_info"`
	VirtualStr           string    `json:"virtual_str"`
	Address              string    `json:"address"`
	Sysdeleted           int       `json:"sysdeleted"`
	Ordersn2             int       `json:"ordersn2"`
	Changeprice          float64   `json:"changeprice"`
	Changedispatchprice  float64   `json:"changedispatchprice"`
	Oldprice             float64   `json:"oldprice"`
	Olddispatchprice     float64   `json:"olddispatchprice"`
	Isvirtual            int       `json:"isvirtual"`
	Couponid             int       `json:"couponid"`
	Couponprice          float64   `json:"couponprice"`
	Diyformdata          string    `json:"diyformdata"`
	Diyformfields        string    `json:"diyformfields"`
	Diyformid            int       `json:"diyformid"`
	Storeid              int       `json:"storeid"`
	Printstate           int       `json:"printstate"`
	Printstate2          int       `json:"printstate2"`
	AddressSend          string    `json:"address_send"`
	Refundstate          int       `json:"refundstate"`
	Closereason          string    `json:"closereason"`
	Remarksaler          string    `json:"remarksaler"`
	Remarkclose          string    `json:"remarkclose"`
	Remarksend           string    `json:"remarksend"`
	Ismr                 int       `json:"ismr"`
	Isdiscountprice      float64   `json:"isdiscountprice"`
	Isvirtualsend        int       `json:"isvirtualsend"`
	VirtualsendInfo      string    `json:"virtualsend_info"`
	Verifyinfo           string    `json:"verifyinfo"`
	Verifytype           int       `json:"verifytype"`
	Verifycodes          string    `json:"verifycodes"`
	Invoicename          string    `json:"invoicename"`
	Merchid              int       `json:"merchid"`
	Ismerch              int       `json:"ismerch"`
	Parentid             int       `json:"parentid"`
	Isparent             int       `json:"isparent"`
	Grprice              float64   `json:"grprice"`
	Merchshow            int       `json:"merchshow"`
	Merchdeductenough    float64   `json:"merchdeductenough"`
	Couponmerchid        int       `json:"couponmerchid"`
	Isglobonus           int       `json:"isglobonus"`
	Merchapply           int       `json:"merchapply"`
	Isabonus             int       `json:"isabonus"`
	Isborrow             int       `json:"isborrow"`
	Borrowopenid         string    `json:"borrowopenid"`
	Merchisdiscountprice float64   `json:"merchisdiscountprice"`
	Apppay               int       `json:"apppay"`
	Coupongoodprice      float64   `json:"coupongoodprice"`
	Buyagainprice        float64   `json:"buyagainprice"`
	Authorid             int       `json:"authorid"`
	Isauthor             int       `json:"isauthor"`
	Ispackage            int       `json:"ispackage"`
	Packageid            int       `json:"packageid"`
	Taskdiscountprice    float64   `json:"taskdiscountprice"`
	Seckilldiscountprice float64   `json:"seckilldiscountprice"`
	Verifyendtime        time.Time `json:"verifyendtime"`
	Willcancelmessage    int       `json:"willcancelmessage"`
	Sendtype             int       `json:"sendtype"`
	Lotterydiscountprice float64   `json:"lotterydiscountprice"`
	Contype              int       `json:"contype"`
	Wxid                 int       `json:"wxid"`
	Wxcardid             string    `json:"wxcardid"`
	Wxcode               string    `json:"wxcode"`
	Dispatchkey          string    `json:"dispatchkey"`
	Quickid              int       `json:"quickid"`
	Istrade              int       `json:"istrade"`
	Isnewstore           int       `json:"isnewstore"`
	Liveid               int       `json:"liveid"`
	OrdersnTrade         string    `json:"ordersn_trade"`
	Tradestatus          int       `json:"tradestatus"`
	Tradepaytype         int       `json:"tradepaytype"`
	Tradepaytime         time.Time `json:"tradepaytime"`
	Dowpayment           float64   `json:"dowpayment"`
	Betweenprice         float64   `json:"betweenprice"`
	Isshare              int       `json:"isshare"`
	Officcode            string    `json:"officcode"`
	WxappPrepayId        string    `json:"wxapp_prepay_id"`
	Cashtime             time.Time `json:"cashtime"`
	Iswxappcreate        int       `json:"iswxappcreate"`
	RandomCode           string    `json:"random_code"`
	PrintTemplate        string    `json:"print_template"`
	CityExpressState     int       `json:"city_express_state"`
}
